### ISSUE TITLE
Crash when navigating to ambiguous note links

### ISSUE THREAD

**Issue by vcavallo** [srid/emanote#111]
Added after: **After re-reading this and testing some more I think the issue is actually: "having any file with a slug that is the inferred path of another file"**. 

----

In the error log below, the file `literature-notes/__literature-notes-index` has the following yaml frontmatter:

```yml
slug: literature-notes
```

```
[Info#WS.Client.69] Connected
[Debug#WS.Client.69] <~~ ["literature-notes.html"]
Ambiguous notes: Identity R[LMLType Md]:literature-notes :| [Identity R[LMLType Md]:literature-notes/__literature-notes-index]
CallStack (from HasCallStack):
  error, called at src/Relude/Debug.hs:218:11 in relude-0.7.0.0-1lCtINbPS6X92nmUAhI15E:Relude.Debug
  error, called at src/Emanote/Model/Note.hs:135:10 in main:Emanote.Model.Note
  singleNote, called at src/Emanote/Model/Type.hs:126:3 in main:Emanote.Model.Type
```

**Describe the bug**

While running the dev server, navigating to an ambiguous "directory index" page hangs the server

**To Reproduce**

In the description below, the name "literature-notes" doesn't matter.

1. Have a directory at the top-level called `literature-notes`
2. Within that directory, have a file (no matter the filename) with yaml frontmatter including `slug: literature-notes`
3. Run the emanote server (`PORT=7779 emanote`)
4. Click on the `literature-notes` directory

**Expected behavior**

Expected this file to be found at the slug described in the frontmatter. Or else for a page to be displayed explaining the problem (similar to what happens with a missing index page)

**Desktop (please complete the following information):**
 - Browser: Firefox 90.0
 - Emanote 0.1.39.0

May be related to Discussion https://github.com/srid/emanote/discussions/107

**Comment by srid** [comment]
A solution here is: instead of crashing the request (with Haskell's `error`), it should just serve a nice error page HTML showing the "Ambiguous notes" message (but don't generate when doing static-site generation).

EDIT: This should also apply for ambiguous wiki-links.

**Comment by srid** [comment]
This is related to #126
