### ISSUE TITLE
Custom Text for Zettels does not work well within a Markdown Table

### ISSUE THREAD

**Issue by Coda-Coda** [srid/emanote#113]
Firstly, thank you so much for the awesome work with emanote - the live rendering is VERY COOL to work with.

**Describe the bug**
Custom Text for Zettels does not work well within a Markdown Table. The table ends up rendering incorrectly.

**To Reproduce**
1. Create test.md
2. Create test2.md
3. Add the following to test2.md
```
| [[test]] | hi  |
| ------- | --- |
|  a      | c   |
|  b      | d   |

| [[test|Hello World]] | hi  |
| ------- | --- |
|  a      | c   |
|  b      | d   |
```
4. The first table will render correctly, but the second will look like: 
![image](https://user-images.githubusercontent.com/5212453/128635371-cc202860-0589-44cd-a210-5f80ce64930c.png)

**Expected behavior**
The second table should render as:
![image](https://user-images.githubusercontent.com/5212453/128635422-e96e9758-cca6-473d-9cd8-ca3d171388f9.png)

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version 90.0.1

**Additional context**
This is using emanote locally, live. I haven't checked but I'm sure emanote gen would have the same issue.

**Comment by chris-sanders** [comment]
I was just noticing this same thing. Obsidian solved this by allowing an escape character before the pipe. I don't love how that looks but it might be the most compatible solution.

**Comment by srid** [comment]
I think this is an unavoidable limitation of Markdown's [table extension](https://github.github.com/gfm/#tables-extension-). You can workaround it by escaping the `|` in the wiki-link using backslash (`\`).

ie.

```markdown
| [[test\|Hello World]] | hi  |
| ------- | --- |
|  a      | c   |
|  b      | d   |
```
