### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by srid** [srid/emanote#152]
- URL parsing (.md and wiki-links) and route encoding/decoding
- Metadata overriding
- Generated HTML is valid https://github.com/srid/emanote/discussions/217
- ...

See also: [reported bugs](https://github.com/srid/emanote/issues?q=label%3Abug+)

**Comment by edrex** [comment]
i'd be interested adding some tests if the test framework were in place

**Comment by srid** [comment]
I'll add one by this weekend.

**Comment by srid** [comment]
@edrex Added one now.

Using https://hedgehog.qa

Run `bin/test` to run the tests.

**Comment by srid** [comment]
we have this now
