### ISSUE TITLE
Official release

### ISSUE THREAD

**Issue by srid** [srid/emanote#153]
Emanote is currently in beta. It is time to cut the first public release.

- [x] WIP -> Beta
- [ ] Finish [milestone tasks](https://github.com/srid/emanote/milestone/3)
- [x] Complete documentation
  - HTML templates
  - Layers
- [x] Release dependent libraries to Hackage
  - [x] heist (as a fork package, due to upstream being unmaintained)
  - [x] tagtree
  - [x] https://github.com/well-typed/ixset-typed/issues/17
  - [x] Ema https://github.com/srid/ema/pull/81
- [x] ~~(Optional) Build Linux static binary using Nix~~
  - [x] Try haskell.nix (including cross-compilation for musl & Windows) #155
- [x] Add to nixpkgs 
- [x] Reduce dependencies
  - [x] Move tests to its own stanza
  - [x] https://github.com/EmaApps/ema/issues/141
- [ ] Demo of Emanote as library
- [ ] Release emanote to Hackage
  - [x] First release
  - [x] Final release
- [ ] Update https://emanote.srid.ca/start/install to mention nixpkgs install (as default?)
- [ ] Blog post and annoucements

**Comment by srid** [comment]
Not gonna bother with static builds, because we still have to figure out a way to distribute default layer along with it (cf. #156). Let package managers worry about it. We'll make emanote available on Hackage, so a simple 'cabal install emanote' would work (as long as non-Haskell dependencies, like tailwind, are installed).

**Comment by srid** [comment]
Heist fork has been put in Hackage, https://github.com/snapframework/heist/pull/130#issuecomment-1086931247

**Comment by srid** [comment]
Now that [Ema 0.8 is released](https://srid.ca/ema-0.8) it is high time we release Emanote to Hackage, just to get it to nixpkgs.

**Comment by srid** [comment]
Emanote is feature-complete enough to make the initial release now.

**Comment by srid** [comment]
Now on Hackage: https://hackage.haskell.org/package/emanote-0.8.0.0

I'd like to wait for a couple of things before making the blog post announcement:

- Add emanote to nixpkgs (perhaps @maralorn may be interested?)
- Add an example that shows how to use Emanote as a library to extend it (I have an idea for creating an invoice maker that uses Markdown tables and backlinks).

**Comment by maralorn** [comment]
@srid What do you envision as "adding to nixpkgs"? We can just use `haskellPackages.emanote`, right?

But I will gladly enter myself as emanote maintainer and make sure that it builds.

**Comment by srid** [comment]
> We can just use `haskellPackages.emanote`, right?

Yea, and maybe a top-level alias as well, so `nix run nixpkgs#emanote` works.

The top-level flake.nix has just [4 overrides](https://github.com/EmaApps/emanote/blob/5aff99c616750ee23c28c0f6eb4f51d7c79a27f6/flake.nix#L37-L40) (disable tests, unmark broken) and emanote itself gets a build dependency on `pkgs.stork` (while [unmarking](https://github.com/EmaApps/emanote/blob/5aff99c616750ee23c28c0f6eb4f51d7c79a27f6/nix/stork.nix#L8) the M1 package from being broken) as well as the `tailwind` Haskell package (which in turn has the [node CLI with plugins](https://github.com/EmaApps/emanote/blob/5aff99c616750ee23c28c0f6eb4f51d7c79a27f6/nix/tailwind.nix#L7-L15) as dependency).

> But I will gladly enter myself as emanote maintainer and make sure that it builds.

That'd be great! :-)

**Comment by maralorn** [comment]
I can only start with that on our next haskell-updates run. I will ping back once the deed is done.

**Comment by maralorn** [comment]
Adressed in nixos/nixpkgs#199442.

**Comment by srid** [comment]
Pending https://github.com/NixOS/nixpkgs/pull/199424

Meanwhile, `nix run github:nixos/nixpkgs/haskell-updates#emanote`

**Comment by srid** [comment]
https://github.com/EmaApps/emanote/issues/372 is the main issue left to resolve before final release.

**Comment by srid** [comment]
Released 1.0!

@maralorn It would be great if you could add 1.0 to nixpkgs. Note that from packaging point of view it involves these changes:

- Depends on new package https://hackage.haskell.org/package/commonmark-wikilink
- We now depend on `heist` directly (not `heist-emanote`)
- We require `ema` >= 0.10 (ema got split into three libraries). This may require adding `self.haskellPackages.ema_0_10_0`?
- `commonmark-extensions  <0.2.3.3` (because the next version has a bug)
