### ISSUE TITLE
Expose JSON dump of notebook metadata

### ISSUE THREAD

**Issue by srid** [srid/emanote#161]
Add `emanote export` so as to be able to export a JSON dump of the graph metadata (including backlink contexts, if requested) of the notebook.

(This would be analogous to `neuron query -g`)

Consider implementing `emanote gen --with-export` so that the dump is generated in the static site as well.

**Comment by edrex** [comment]
i'm plotting a command-line wiki refactoring tool (ops like rename/move with link rewriting, subgraph-based wiki splitting, document format linting), and access to emanote's link graph would be interesting.

**Comment by srid** [comment]
For those looking to implement this, my initial thought is that we *essentially* only need to convert these three fields in the model to JSON:

https://github.com/srid/emanote/blob/149774c7d0bce92f2a55d32e9834ab5812fc9cb9/src/Emanote/Model/Type.hs#L46-L48

(The first provides the notes themselves, including the parsed Pandoc AST; the second provides the relationships between notes; the third provides the YAML metadata).

In addition to adding a CLI command that invokes runs `Source.emanate` in an one-off manner (to get the initial model).

**Comment by srid** [comment]
@edrex The linked PR (in draft form) #174 implements some version of the export feature. Could you try it out for your use cases and provide feedback?

You can clone that branch and run `nix-env -if ./default.nix` (or `nix-build -o ./output`) to use that custom Emanote. Then, either in live server or generated static site, access the URL path `/-/export.json` to get the graph in JSON. It should look like this (with [the formatter](https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa/related?hl=en)):

![image](https://user-images.githubusercontent.com/3998/136713137-241b126f-1ccc-4488-a7e3-4b3f7431932b.png)

(This includes only the relations, and I'll shortly expose the note metadata as well).

**Comment by edrex** [comment]
Tested briefly on my big messy wiki. It's fast, presumably exposing an existing in-memory structure.

Impressions:

- `tag: RTMissing` edges lack contents field, which would be handy for enumerating missing link targets:

```
> curl -s http://localhost:8000/-/export.json|jq '[.[] | select(.[1].tag == "RRTMissing")][-1]' 
["jq.md", {"tag": "RRTMissing"}]
```

- `/-/export.json` is present in the generated output as well, making it available to eg, build a force-directed graph client-side, which seems like a fun possibility

Reading and understanding Haskell is a very slow process for me rn so I can't comment on the code.

**Comment by srid** [comment]
@edrex I addressed your first comment, as well as added the note metadata ... in addition to normalizing and structure-ifying the JSON. Try out the PR once more and let me know any further feedback you have!

EDIT: Also, the route has changed to `/-/export/graph.json`

**Comment by srid** [comment]
https://github.com/srid/emanote/pull/174
