### ISSUE TITLE
Wikilinks of the form [[Page#Heading]] have no text in output

### ISSUE THREAD

**Issue by edrex** [srid/emanote#168]
Obsidian-style `[[Page#Heading]]` links end up with empty body text:

```
<a href="bar#fooo" 
   class="text-blue-600 font-bold hover:underline"
   data-wikilink-type="WikiLinkNormal"
></a>
```
so they aren't visible in the rendered document.

Seems like a bug, with the desired behavior depending on whether these heading links should be supported.

1. As an initial fix, maybe just keep the text as-is, optionally stripping the `#fragment-id` (heading ids are transformed from `Heading Text` => `heading-text` in the output so they won't work as-is anyway)
2. Include the transformed fragment ID in the output href
3. (non-trivial) Add broken-link checking for headings (seems like a pretty low value/effort ratio tho)

(found while checking if `#hashtags` in wiki links are parsed as in #166)

https://help.obsidian.md/How+to/Internal+link#Link+to+headings

**Comment by srid** [comment]
> (non-trivial) Add broken-link checking for headings (seems like a pretty low value/effort ratio tho)

See https://github.com/srid/emanote/discussions/105

**Comment by srid** [comment]
For now we just ignore the anchors (so `[[Page#Heading|some text]]` will render as a link to Page.md with "some text" as link text), but see #105 for actually handling the anchors.
