### ISSUE TITLE
Emanote doesn't render WebP

### ISSUE THREAD

**Issue by j-steinbach** [srid/emanote#170]
I link a [webp](https://en.wikipedia.org/wiki/WebP) image like [this](https://note.ema.srid.ca/demo/embed#images) and expect it to render:

```
![[series.squid-game.webp]]
![Img](../assets/series.squid-game.webp)
```
This is the result:

![2021-10-08_13-51-emanote-webp-render](https://user-images.githubusercontent.com/69524139/136552222-5ea2111f-bb3e-49c3-b7a0-8301bc515f3b.png)

It appears to me as if Emanote doesn't treat `.webp` as images but as files instead.

Hovering over the first link (with [Imagus](https://addons.mozilla.org/en-US/firefox/addon/imagus/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)) correctly displays the image. Same with clicking on it. I therefore believe that I didn't mistype the path or something.

To test: [This](https://upload.wikimedia.org/wikipedia/commons/a/a1/Johnrogershousemay2020.webp) is a webp image.

**Comment by srid** [comment]
Should be fairly simple to resolve by adding `.webp` to this list:

https://github.com/srid/emanote/blob/149774c7d0bce92f2a55d32e9834ab5812fc9cb9/src/Emanote/Pandoc/Renderer/Embed.hs#L86-L94
