### ISSUE TITLE
Can't create empty cells in first column in markdown table

### ISSUE THREAD

**Issue by j-steinbach** [srid/emanote#193]
I want to create a markdown table where some cells in the first column are empty.

![2021-11-08_14-42](https://user-images.githubusercontent.com/69524139/140752905-407626ef-b9bc-4306-a6e8-e4ed5c2fa379.png)

This is my markdown code:

```markdown
area | category
-- | --
00-09 | 
| 01 
| 02
- | 03 
- | 04
- | 05
```

I am actually not sure which markdown spec Emanote uses. I base my bug report on GFM. As demonstrated in [199](https://github.github.com/gfm/#example-199), cells don't need leading or trailing pipes. 

---

E: Interestingly Github itself doesn't seem to follow its spec.. :nauseated_face: So I guess this is a *wontfix*. 

area | category
-- | --
00-09 | 
| 01 
| 02
\- | 03 
\- | 04
\- | 05

**Comment by srid** [comment]
Add an extra pipe; it will work:

area | category
-- | --
00-09 | 
| | 01 
| | 02
\- | 03 
\- | 04
\- | 05

**Comment by j-steinbach** [comment]
This is a workaround, but I won't complain. (Or will I? :thinking:)

---

Just for the record: 

I guess Emanote uses ["Zettel Markdown"](https://neuron.zettel.page/markdown). This leads to [commonmark pipe tables](https://github.com/jgm/commonmark-hs/blob/master/commonmark-extensions/test/pipe_tables.md), finally leading to *A leading and trailing pipe is also recommended for clarity of reading, and if there's otherwise parsing ambiguity*. So I guess theoretically I am right, and this *is* a bug, but factually no one will fix this, as the markdown parser is a convoluted mess and I (we) am stuck doing `| |`.. :/

**Comment by srid** [comment]
I'm a fan of https://asciidoctor.org - but unfortunately I don't think there is a good and complete Haskell parser for it yet.

I don't know how complete https://github.com/gmarpons/asciidoc-hs is as of now. Maybe someone can investigate.
