### ISSUE TITLE
Fonts don't look as good on macOS

### ISSUE THREAD

**Issue by srid** [srid/emanote#197]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/3998/142791106-7bbe02d0-709e-4886-8483-78f55228fb1b.png">

**Comment by j-steinbach** [comment]
Can you add a "good" image for comparison? On the first glance this doesn't look "bad".

**Comment by srid** [comment]
Here's how it looks on Linux. Notice the lack of clear contrast between bold and regular text.

![image](https://user-images.githubusercontent.com/3998/142968045-3b9ba81c-6902-4b86-a9ca-f0e2e8dbab8f.png)

**Comment by j-steinbach** [comment]
Ah, I see it. The Linux font looks crisper, the Mac one is way thicker.

For anyone having trouble seeing it: compare the `Emanote is currently in beta phase` lines. 

One good technique for comparison is to download the pictures, and then switching between them quickly.

[Ideally I knew how to create a GIF with the comparison.. :smile_cat: ]

**Comment by srid** [comment]
We could switch to a different font that looks good on all OS.

Doing this is in Emanate should be trivial. We just replace the font files [here](https://github.com/srid/emanote/tree/master/default/_emanote-static/fonts), and change their reference [here](https://github.com/srid/emanote/blob/6791d474eb412befb5b9555f6c13c28006fea798/default/templates/hooks/more-head.tpl#L2) and [here](https://github.com/srid/emanote/blob/f758bea962954ebdede872f018d19d2192153d52/default/_emanote-static/inverted-tree.css#L15).

**Comment by j-steinbach** [comment]
I don't have a Mac, so I can't test this, but are you sure that it is simply "Nunito doesn't look good on MacOS"? There are a few things that come to my mind:

- Does this happen only on your single machine? Or does it happen across all Apple devices?
- It might be an issue with Retina displays -> [Fix blurry fonts](https://www.cleverfiles.com/help/mac-fonts-text-blurry.html) (Note: This is literally a random link I just came across)
    - Does this happen on each screen resolution?
- Does this also happen with the default font-fallback and/or Mac-only fonts?
- Does this happen on different browsers?

I am no expert on fonts/typography, but I do enjoy wasting my time and [playing with it](https://github.com/j-steinbach/having-fun-with-nixos-logos/blob/master/out/RixOS-logo.png). Fonts are a rabbit-hole, and I heavily recommend against diving down the burrows and searching the perfect font when we are not sure yet that this doesn't happen with all/most fonts on MacOS.

**Comment by srid** [comment]
> are you sure that it is simply "Nunito doesn't look good on MacOS"? 

I don't know really, I haven't investigated the problem. Maybe it is something to do with our use of font weights.

The screenshot I posted above is from M1 MacBook Air, running macOS Monterey and Safari browser in default configuration (nothing customized).

> I heavily recommend against diving down the burrows and searching the perfect font when we are not sure yet that this doesn't happen with all/most fonts on MacOS.

Agreed.

**Comment by j-steinbach** [comment]
Re: GIF 

Actually quite simple: `convert -delay 100 -loop 0 *.jpeg animatedGIF.gif`.

Ideally the images have an identical size & viewport, but I think this demonstrates the issue quite well:

![font-comparison](https://user-images.githubusercontent.com/69524139/143059342-c59e6f07-a135-4719-b16a-e670c4b026b2.gif)
