### ISSUE TITLE
modelFolgezettelAncestorTree doesn't terminate with reciprocal parent links

### ISSUE THREAD

**Issue by edrex** [srid/emanote#210]
I'm seeing runaway CPU usage running the server or gen with a test case consisting of an `index.md` linking with `#[[foo]]` to `foo.md` (https://gist.github.com/2e5117e799c17d5363f302615489195f)

 Doesn't happen if
  - if `foo.md` doesn't exist
  - with `index.md` renamed to `i.md`
  - with a non-parent link `[[foo]]`

Reproducible? I see it with builds of emanote-0.3.10.3 and emanote-0.3.15.3 from nix (where do those versions come from?)

**Comment by srid** [comment]
I pushed a commit yesterday for that version, see https://github.com/srid/emanote/commit/796a8175a5780dba1e4efc09e94e7973820657c6

Can you try with an older version of Emanote? 

Try: `nix run github:srid/emanote/8aeb9892aa7ac2bd5c99050e07a35339c12bf6a5` to get 0.3.15.2.

**Comment by edrex** [comment]
Actually saw it first with 0.3.10.3 6716d8d12961b98cb1f7b468a4d206b52e783293
 so it's been around at least since then. An uplink from index isn't something most people would try so maybe it's not a regression.

**Comment by edrex** [comment]
```
cabal run --enable-profiling exes -- -L ./testcase +RTS -p ^C
cat emanote.prof | ghc-prof-flamegraph > emanote-profile.svg
```
[![](https://gist.githubusercontent.com/edrex/2e5117e799c17d5363f302615489195f/raw/e2e6a19a3a54df0d738a76f4fe1cc81814050326/emanote-profile.svg)](https://gist.githubusercontent.com/edrex/2e5117e799c17d5363f302615489195f/raw/e2e6a19a3a54df0d738a76f4fe1cc81814050326/emanote-profile.svg)

**Comment by edrex** [comment]
Oh, i think the unbounded recursion is because Foo has index as ancestor implicitly.
This lead me to check if a simple reciprocal reference loop `foo.md` => `#[[bar]]`, `bar.md` => `#[[foo]]` terminates and in fact it doesn't, so the issue is that the folgezettel tree needs loop detection.

**Comment by srid** [comment]
Yea, it just loops indefinitely. To reproduce with log:

```diff
diff --git a/docs/index.md b/docs/index.md
index fdb620a..6ca4fe7 100644
--- a/docs/index.md
+++ b/docs/index.md
@@ -6,6 +6,8 @@ page:
 ---
 # Emanote
 
+See #[[examples]]
+
 :::{.text-xl .my-4}
 [Emanote][gh] enables you to **create beautiful websites** -- such as *personal webpage*, *blog*, *wiki*, *Zettelkasten*, *notebook*, *knowledge-base*, *documentation*, etc. from future-proof **plain-text notes** and arbitrary data -- with live preview that updates in real-time. It aims to be next-gen [neuron](https://neuron.zettel.page/) with powerful features.
 :::
diff --git a/src/Emanote/Model/Graph.hs b/src/Emanote/Model/Graph.hs
index c08fabf..06368ce 100644
--- a/src/Emanote/Model/Graph.hs
+++ b/src/Emanote/Model/Graph.hs
@@ -40,7 +40,7 @@ modelFolgezettelAncestorTree r0 model =
               <> folgezettelFrontlinks
               -- Folders are automatically made a folgezettel
               <> maybeToList (parentLmlRoute =<< leftToMaybe (R.modelRouteCase r))
-      fmap catMaybes . forM folgezettelParents $ \parentR -> do
+      fmap catMaybes . forM folgezettelParents $ \(traceShowId -> parentR) -> do
         let parentModelR = R.liftModelRoute . R.lmlRouteCase $ parentR
         gets (parentModelR `Set.member`) >>= \case
           True -> pure Nothing
```

`bin/run` will see a flurry of:

<img width="268" alt="image" src="https://user-images.githubusercontent.com/3998/145119164-f9c9dab2-c73f-46d0-9ab8-8cabd3f2d73b.png">

**Comment by srid** [comment]
@edrex I think I know where the bug is. But would you like to take the opportunity to contribute a PR? :-) VSCode is a nice experience.

Hint: we use the State monad (`MonadState`) to track "already visited" nodes when building the tree (see `modify` use), so most of the code to avoid infinite loop is already there; just with a tiny bug.

**Comment by edrex** [comment]
Ok, I'm taking a look.
