### ISSUE TITLE
No DOCTYPE in generated HTML

### ISSUE THREAD

**Issue by kukimik** [srid/emanote#216]
**Describe the bug**
The generated HTML filles lack the `<!DOCTYPE html>` declaration.

**To Reproduce**
1. Follow the instructions at https://note.ema.srid.ca/start/install/docker.
2. Open the generated HTML files in your favourite text editor and check the first line.

The pages published at https://note.ema.srid.ca/ are also affected by this bug.

**Expected behavior**
The generated HTML files should start with the following text:

`<!DOCTYPE html>`

**Desktop (please complete the following information):**

- Emanote 0.3.15.2 used via docker on Linux.

**Additional context**

About the DOCTYPE: https://developer.mozilla.org/en-US/docs/Glossary/Doctype

Note that the text `<!DOCTYPE HTML>` is present in `base.tpl`. I don't know why it is not included in the generated HTML.

I believe this should be fixed before the 1.0 release.

**Comment by srid** [comment]
DOCTYPE is used in the Heist template,

https://github.com/srid/emanote/blob/bc574c1e5c3a28f1ab1174691ca9f8c1e595b4d6/default/templates/base.tpl#L1

But it is not being generated for some reason,

https://github.com/srid/emanote/blob/9e89c60bb285dd6a15a7387a6b94d4a0d82c7104/index.html#L1

Requires debugging ... probably something to do with heist.
