### ISSUE TITLE
`srid.ca` has an SSL issue

### ISSUE THREAD

**Issue by Fullchee** [srid/emanote#222]
**Describe the bug**

**To Reproduce**
- Go to https://note.ema.srid.ca/start/install
   - the link in the README

**Expected behavior**
- it would lead me to a webpage

**Screenshots**

![image](https://user-images.githubusercontent.com/11246258/148072880-ee2f528c-bc86-4d54-83a3-1f6769e2fcb4.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version:  96.0.4664.110

**Comment by srid** [comment]
I migrated domains / DNS from Google to Namecheap/Cloudflare. Let's give it a couple of days to resolve itself. If not, I'll have to contact Cloudflare support.

**Comment by srid** [comment]
The website is built off https://github.com/srid/emanote/tree/master/docs - so meanwhile, you can read the .md files.

**Comment by srid** [comment]
https://emanote.srid.ca should be up. If not, try again in a few hours.

**Comment by srid** [comment]
https://emanote.srid.ca is the new canonical URL.

**Comment by Fullchee** [comment]
Works for me! Thank you!
