### ISSUE TITLE
emanote hangs when browsing some pages

### ISSUE THREAD

**Issue by Terkwood** [srid/emanote#240]
**Describe the bug**

Emanote will often hang when browsing pages with uplinks.  

I use the neuron-style interface for emanote. 

Here's the problem: If I trim the various uplinks and downlinks from the page, it starts to load.  Specifically, if the problem link is an uplink like `#[[foobar]]`, converting it to a non-hierarchical link like `[[foobar]]` seems to fix the issue.

**To Reproduce**
1. Create a lot of pages in neuron-style configuration.
2. Add multiple uplinks to each page.
3. Browse around until a page hangs.

**Expected behavior**
Loading a page shouldn't cause the server to hang.

**Screenshots**

I'll see the emanote terminal session print something like this:

```
[Info#HTTP] ["my-fancy-note.html"] as Just R[/my-fancy-note.md]
```

<img width="766" alt="Screen Shot 2022-01-25 at 9 23 56 AM" src="https://user-images.githubusercontent.com/38859656/150994940-df985333-39a4-4362-a31a-9ede43df35f9.png">

**Desktop (please complete the following information):**
 - Browser: Chrome, Brave, Firefox.  This doesn't seem to be related to the browser.
 - Version 0.3.9.1 and several other recent versions in the last 6 months.

**Comment by Terkwood** [comment]
Updated the description with a bit more info

**Comment by srid** [comment]
@Terkwood Are you using the latest version of Emanote? A similar bug was fixed before - #210.

**Comment by Terkwood** [comment]
Oh, nice!  I'm pretty up to date but I might not be _that_ up to date.  Will check back and let you know.

That bug in #210 does describe at least _some_ of my problem situations -- I found a very obvious cycle of DocumentA pointing to DocumentA.  Bad note taking on my part!  Anyway, this looks hopeful, thanks!

**Comment by Terkwood** [comment]
Just updated to the latest version used in your main branch, and it's working flawlessly... even with my hopelessly looping note hierarchies.  Thanks for the great software!
