### ISSUE TITLE
cache miss evaluating flake

### ISSUE THREAD

**Issue by edrex** [srid/emanote#274]
Follow up to #273.

I get a cache miss with `nix run github:srid/emanote`. I notice the working copy in the store has a different hash, so i suspect there's some slight content difference in the the source dir. Trying to investigate.

**Comment by edrex** [comment]
https://github.com/Gabriel439/nix-diff/issues/56

**Comment by srid** [comment]
https://github.com/srid/emanote/runs/5824813994?check_suite_focus=true

In CI, the derivation built, and that uploaded to cachix are the same:  `/nix/store/llwxjnbwhg8gmj2dyvr6vn5ah7xmrjcq-emanote-0.5.6.0`

But the local git working copy derivation is different:

```
❯ nix-build --no-out-link
/nix/store/54a2m6ky8cqsv99m2bwckl101pbyrfpp-emanote-0.5.6.0
```

---

Incidentally, the CI is also pushing ~700MB of docker image derivation to cachix! That should be avoided.

```
  compressing and pushing /nix/store/vsnbwhhascaywjx8v0pqmagp8fnzmhfa-docker-image-emanote.tar.gz (665.63 MiB)
```

**Comment by srid** [comment]
Okay, 56913b3909f41b944be4e575e17c8f8b9e17f749 did not help.

**Comment by srid** [comment]
Hercules produces the right hash. I suspect something's wrong with GitHub Actions environment.

**Comment by edrex** [comment]
Yeah, I suspect something in `.git`, such as `HEAD` pointing to a branch instead of a commit. IDK if nix does any normalization there.

I think `nix-diff` is supposed to be able to point out such differences, but I haven't figured out how to copy the closure locally to compare.

**Comment by edrex** [comment]
Does Hercules provide builder nodes, or do you have to bring your own?

**Comment by edrex** [comment]
`nix run` fetches emanote from the cache now, i guess because of a Hercules build. Is this fixed?

**Comment by edrex** [comment]
- ~~[ ] TODO(edrex): repro with a minimal test flake repo and file an issue upstream (cachix action maybe)~~

**Comment by srid** [comment]
https://github.com/srid/emanote/commit/78849509475f5225e12ddb25009b9f2a6a6b63f7 seems to have resolved it. 🤷🏿

**Comment by edrex** [comment]
No upstream bug is a resolution worth celebrating (unfortunately rare for me these days, as I'm spending lots of time following bugs upstream). Thanks!
