### ISSUE TITLE
Wiki link w/ custom text breaks lists formatting

### ISSUE THREAD

**Issue by Mowd** [srid/emanote#28]
Wiki link with alternative preview text will cause incorrect rendering in list.

```
Input:

- [[2021-05|202105]]
- [[2021-04|202104]]
- [[2021-03|202103]]
- [[2021-02|202102]]
- [[2021-01|202101]]

Output:

202105
- 20210
202103
- 202102
202101
```

![image](https://user-images.githubusercontent.com/1097892/119433908-ba40c000-bd49-11eb-880d-f0c245d36e35.png)

**Comment by srid** [comment]
Might be related: https://github.com/jgm/commonmark-hs/issues/52
