### ISSUE TITLE
`nix run` misses Garnix cache

### ISSUE THREAD

**Issue by edrex** [srid/emanote#293]
It looks like the cache isn't populated, at least for HEAD.

`nix run github:srid/emanote` tries to fetch all the dev deps and build.

Ref https://github.com/srid/emanote/pull/288, https://github.com/srid/emanote/issues/274 (prob a different root cause tho)

**Comment by srid** [comment]
Linux?

**Comment by srid** [comment]
On x86-64_linux, I do see garnix cache being used. Perhaps you are on M1? If so, it is disabled because of https://github.com/garnix-io/issues/issues/17

**Comment by edrex** [comment]
My mistake, it was actually just fetching runtime dependences, such as ghc-doc (?). i just assumed that a 7.8GB closure must be dev deps. I would love to do more Haskell, it's just these runtime closure sizes I can't fathom.

**Comment by srid** [comment]
That's one thing that sucks about Haskell Nix infra in its current state, though there are ways to reduce the closure size; see https://github.com/srid/neuron/issues/193

**Comment by edrex** [comment]
Oof, I'm realizing reading through related neuron issues and nixpkgs issues/discussions that this is a deep and thorny topic. Would it make sense to create a meta-issue for tracking various routes to reducing the runtime closure size, similar to srid/neuron#193? This isn't something I can dig into at the moment, but my dev workflow would hugely benefit from progress.

**Comment by srid** [comment]
Sure go ahead
