### ISSUE TITLE
`emanote run` uses port `0`

### ISSUE THREAD

**Issue by edrex** [srid/emanote#294]
`emanote run` without a port specified uses the special value `0` to ask the OS to choose a port, which is fine. But it doesn't find out what the port is, so it outputs:

```
[Info#ema] Ema live server running: http://127.0.0.1:0
```

```
lsof  -iTCP -sTCP:LISTEN
emanote   219844 edrex   26u  IPv4 1494347      0t0  TCP localhost:44725 (LISTEN)
```

**Comment by srid** [comment]
Oh, that's strange. When you run just `emanote` (without the 'run' argument) it behaves correctly. Looks like a bug in the command-line argument parser, as `0` shouldn't be used in the first place.

https://github.com/srid/ema/blob/multisite/src/Ema/CLI.hs
