### ISSUE TITLE
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override

### ISSUE THREAD

**Issue by tintin10q** [srid/emanote#300]
**Describe the bug**
When I tried to install I get `error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override`

**To Reproduce**
1. Install nix 
2. Run `nix profile install github:srid/emanote`

**Expected behavior**
I would expect the command to work. You like you suggest it will on your how to install page here https://emanote.srid.ca/start/install

**Desktop (please complete the following information):**
 - Ubuntu 18.04.6 LTS

**Comment by tintin10q** [comment]
I had to run `nix profile install github:srid/emanote --extra-experimental-features nix-command --extra-experimental-features flakes` for it to work. If this is now what is needed you should update the installation guide.

**Comment by srid** [comment]
I will update that documentation page, but you need to enable flakes by following the instructions here: https://nixos.wiki/wiki/Flakes#Installing_flakes

**Comment by srid** [comment]
This part I think,

<img width="497" alt="image" src="https://user-images.githubusercontent.com/3998/173082639-6777fe2f-7f83-4986-9643-5aba4e00783a.png">

**Comment by tintin10q** [comment]
Ok I will try that

**Comment by tintin10q** [comment]
Thanks for updating this. Could you explain what the Nix cache does?

**Comment by srid** [comment]
Using the Nix binary cache will generally avoid compiling the software and its dependencies ... and instead, pull the built binaries directly from the binary cache specified. I'll add this to docs.

**Comment by danielkrajnik** [comment]
Can someone please explain what needs to be appended where?
I've just tried running ```nix search librewolf``` and it yielded a similar error.
I've tried adding ```extra-experimental-features = flakes``` to ```~/.config/nix/nix.conf```, but it didn't do anything
it would be really helpful if nix had this functionality, which someone unfamiliar with the project would expect to work out of the box work out of the box

**Comment by srid** [comment]
@danielkrajnik See the instructions in this section: https://nixos.wiki/wiki/Flakes#Enable_flakes
