### ISSUE TITLE
Vi/Vim/Neovim's writebackup (e.g `filename.md~`) confuses emanote

### ISSUE THREAD

**Issue by applejag** [srid/emanote#316]
**Describe the bug**
Editing files in neovim is unstable.

When having writebackup enabled (`:help writebackup`, which is enabled by default in vi, vim, and neovim), the editor will copy the target to an ephemeral backup file with the same filename but ending with a tilde (such as `filename.md~`) before overwriting the original file.

This seems to confuse emanote as there's not two files with the same name but different extensions, and in some race-condition cases emanote returns 404 on the page after the `md~` backup file was removed.

Suggest adding these backup files hardcoded to the ignore list (<https://github.com/EmaApps/emanote/blob/f89a0697/src/Emanote/Source/Pattern.hs#L34-L40>). There won't really be a case where these should be included.

**To Reproduce**
1. Start `emanote run`
2. Edit markdown file in vim
3. Do some editing
4. Save via `:w`
5. See logs of `emanote run`. Repeat step 3-4, with just minor edits, to try reproduce race condition where emanote in web browser says the page doesn't exist

**Expected behavior**
Saving an edited file via vim to not sometimes mark the file as "404", even though it's still there. 

**Desktop (please complete the following information):**
 - Browser Firefox
 - Version 102.0

**Additional context**

This can be worked around by running `:set nowritebackup` (or `:set nowb` for short), which will disable this backup checking behavior. Would not recommend permanently adding this to your vimrc file though as the writebackups is a good feature for preventing data loss.

If there was `.emanoteignore` files, as proposed in #228, then that would've helped as well.

Also, some fun logs from emanote after editing the `index.md` file a little:

```log
[Info#emanote] [15:16:20] Re-registering file: /home/kalle/Documents/notes/content/4913 R[/4913]
[Info#emanote] [15:16:20] Reading file: /home/kalle/Documents/notes/content/index.md
[Info#emanote] [15:16:20] Re-registering file: /home/kalle/Documents/notes/content/index.md~ R[/index.md~]
[Info#emanote] [15:16:23] Re-registering file: /home/kalle/Documents/notes/content/4913 R[/4913]
[Info#emanote] [15:16:23] Re-registering file: /home/kalle/Documents/notes/content/index.md~ R[/index.md~]
[Info#emanote] [15:16:23] Reading file: /home/kalle/Documents/notes/content/index.md
[Info#emanote] [15:16:27] Re-registering file: /home/kalle/Documents/notes/content/4913 R[/4913]
[Info#emanote] [15:16:27] Re-registering file: /home/kalle/Documents/notes/content/index.md~ R[/index.md~]
[Info#emanote] [15:16:27] Reading file: /home/kalle/Documents/notes/content/index.md
```

**Comment by srid** [comment]
@jilleJr About the "fun logs" see #180
