### ISSUE TITLE
Default wiki-link text should be note's title

### ISSUE THREAD

**Issue by srid** [srid/emanote#33]
If the note has a level-1 heading use that (over filename sans ext) as the link inner text. But do so only if level-1 heading comes as the *first* AST node.

(This already works for sidebar links; just not yet for pandoc links).

Of course if the user provides one explicitly (as in, `[[Foo|some text]]`) _always_ use the user-provided one.

**Comment by srid** [comment]
Probably should happen here, by looking `Note` from `Model` and then using its title:

https://github.com/srid/emanote/blob/f14704cb56da1c8b5741d08ef92f6b5f18a73bb8/src/Emanote/Template.hs#L122-L146

**Comment by ranafathi** [comment]
Hi, Sridhar! I would love to give this a try, can you please walk me through more details?

**Comment by hi-learn-triz-and-usit** [comment]
What is used for determining the link? The file name or the level-1 heading?

**Comment by hi-learn-triz-and-usit** [comment]
> But do so only if level-1 heading comes as the _first_ AST node.

I assume frontmatter is explicitly ignored?

Would it make sense to add an optional explicit title field to the frontmatter?

**Comment by srid** [comment]
Hi @ranafathi - Sure, happy to ... are you familiar with Haskell? Feel free to drop by in the [Matrix chat](https://app.element.io/#/room/#neuron:matrix.org) for this project.

> What is used for determining the link? The file name or the level-1 heading?

Link is *always* determined from filename. I don't see why anybody would want to link to using text other than filenames (it would be confusing), but that discussion is outside the scope of this issue.

> Would it make sense to add an optional explicit title field to the frontmatter?

Neuron does this ... so I guess yes, but I'm not a big fan personally, except for accomodating some Zettelkasten editors that support this (Zettlr I think?).

Incidentally, there is also "site title" that can be set in frontmatter, or - better - in the yaml, which via "data cascade" can apply the site title to all files in a subfolder. https://github.com/srid/emanote/blob/f14704cb56da1c8b5741d08ef92f6b5f18a73bb8/default/index.yaml#L35-L37

So when allowing title to be overriden in metadata (frontmatter or yaml), there is a risk of setting `title` in a .yaml file, and have that apply to all notes under that path (an undesired effect, generally).

**Comment by srid** [comment]
> Link is always determined from filename

Note that there are two kinds of links here. Markdown links (of which wiki-links are part of) and generated HTML links. I was talking about the former; as for the latter: it is derived from the former (Foo.md -> Foo.html) - but can be overridden using `slug` meta (need to open issue on this), like neuron supports.

**Comment by srid** [comment]
> it is derived from the former (Foo.md -> Foo.html) - but can be overridden using `slug` meta (need to open issue on this), like neuron supports.

The default value, which is derived from markdown route, basically replaces ".md" with ".html". But -- in order to obviate setting `slug` for every .md file just to get clean URLs -- I'd like to see sophisticated translations, like lowercasing and converting whitespace to hyphens - but this is not a easy problem, because although you can straightforwardly encode a route to 'clean' URL, it will be ambiguous to decode it back (eg: two files "Foo Bar.md" and "Foo-bar.md" while distinct will map to the same URL). Other translation rules can be devised to avoid this ambiguity; for eg. keep case, but convert whitespace to `+` character, and prevent markdown filenames from having `+` in them.
