### ISSUE TITLE
Fix font flickering

### ISSUE THREAD

**Issue by srid** [srid/emanote#357]
Not a problem with Github Pages but with most other hosts (eg: nginx on cloud), there is a perceptible font flickering on **every** page load.

https://en.wikipedia.org/wiki/Flash_of_unstyled_content

After talking to @toastal ... `font-display: swap;` is a place a look. The use of a (large) variable font might be a factor as well. Needs investigation and resolution.

**Comment by toastal** [comment]
Consider using `src: local("My Font"), url("path/to/font/file/myvariablefont.woff2") format("woff2-variations")` with WOFF2 instead of TTF

**Comment by srid** [comment]
> Consider using `src: local("My Font"), url("path/to/font/file/myvariablefont.woff2") format("woff2-variations")` with WOFF2 instead of TTF

I tried that with https://google-webfonts-helper.herokuapp.com/fonts/work-sans?subsets=latin - but variable fonts no longer work.

i.e., instead of:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/3998/198839352-7f07fd3a-0327-4688-a980-b0df23e90f95.png">

I now see:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/3998/198839364-65d9183a-3f80-43ee-9693-32ff276ff4ca.png">

**Comment by toastal** [comment]
Which part? WOFF2 or local or flickering or font-display?
-- 
toastal ไข่ดาว | https://toast.al
PGP: 7944 74b7 d236 dab9 c9ef  e7f9 5cce 6f14 66d4 7c9e

**Comment by srid** [comment]
#364 fixed it! Cause: preload URL was incorrect.

Would be nice if Emanote's link checker checked for these `href`'s too ...
