### ISSUE TITLE
Org Mode not having frontmatter is a feature, not a bug

### ISSUE THREAD

**Issue by toastal** [srid/emanote#363]
**Describe the bug**
I see a philosophical issue in this project to have metadata is handled by reading the section about [Org Mode](https://emanote.srid.ca/guide/orgmode).

> ## Limitations
>
> While `#+TITLE` is recognized, other metadata are not recognized (yet). Org Mode has no notion of a "frontmatter", therefore you must store file-associated metadata in a separate YAML file. 

[Org Mode provides metadata](https://orgmode.org/manual/Export-Settings.html)—as indicated by the “yet”. When you read the docs for [AsciiDoc](https://docs.asciidoctor.org/asciidoc/latest/document/metadata/) or [reStructuredText](https://docutils.sourceforge.io/docs/ref/rst/directives.html#metadata), these formats have metadata too. When I make an ODF document in LibreOffice I can attach metadata through the document properties. I can do the same with SVGs in Inkscape. I can add metadata to a RAW image through the metadata panel in Darktable. The point is: first-class, in-document metadata is the default, not the exception.

The limitation in the case of metadata lies in Markdown. Frontmatter is not a standard across tools and it’s not portable. This is why the [architecture](https://github.com/EmaApps/emanote/blob/master/docs/architecture.md) page on GitHub renders with a table that is confusing at first glance—and when using AsciiDoc on a Git forge, rendering the metadata can be skipped in these contexts because metadata is a part of the base syntax and not an ad-hoc addition so the consuming tool has awareness. If any formats should require a sidecar file for metadata, it would be the formats that doesn’t support metadata.

**To Reproduce**
1. Go to https://emanote.srid.ca/guide/orgmode
2. Read “Limitation”

**Expected behavior**
There should not be a clause about Org Mode lacking frontmatter as a limitation— just state that the metadata support is a work-in-progress there’s an unfortunate temporary workaround (sidecar file). There should be a section in the Markdown explaining that frontmatter while supported is not portable or standardized across tools and to expect render to break sometimes and that all syntaxes from other tools cannot reasonably be expected to be compatible. The project should *expect* formats to come with metadata and treat those without as the exception with workarounds—not workarounds for the formats with metadata already.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Browser LibreWolf
 - Version 106

**Additional context**

While documentation-wise this could be a tiny change to not make Org Mode seem as oddly inferior when it has a more robust feature set, I feel this is a fundamental issue on how Markdown and its menagerie of tooling is put on a pedestal. You see a lot more tools around Markdown specifically because of all of its limitations where these other formats—Org Mode, AsciiDoc, reStructuredText—their tools give them so much more and their syntaxes are robust enough that you rarely need to reinvent concepts like metadata, imports, admonitions, collapsible blocks, etc. I would expect their features would be elevated and embraced.

**Comment by srid** [comment]
Aside from the documentation change here, I do think the entire configuration can be revamped in a fashion it is not tied to YAML, but simply to some generic hierarchical structure.
