### ISSUE TITLE
Mermaid diagrams appear to be broken

### ISSUE THREAD

**Issue by oinoom** [srid/emanote#370]
It appears that the mermaid diagrams at [this link](https://emanote.srid.ca/tips/js/mermaid) no longer render. I'm not blocking any javascript and am not sure what the cause could be. `mermaid.min.js` seems to load just fine.

**To Reproduce**
1. Go to https://emanote.srid.ca/tips/js/mermaid

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: 105.0.3

**Comment by srid** [comment]
[That sucks](https://srid.ca/nojs). Same behavior on Brave on macOS. We have to fix this for release. Could use some help here!

**Comment by oinoom** [comment]
Unfortunately I can't promise any commitment, otherwise I would jump in. Hope to see it resolved soon, thanks for the attention.

**Comment by kukimik** [comment]
For what it's worth, swapping the order of the following two lines in the frontmatter:

```
    <snippet var="js.highlightjs" />
    <snippet var="js.mermaid" />
```

fixes the problem for me. If you see this as a valid fix, this should probably be described in the docs.

**Comment by srid** [comment]
Doesn't look like that (929759feb5c0c1e88efeb32c20fcd1a8d098cf4c) resolved it.

**Comment by kukimik** [comment]
Hmm, it must have been a coincidence then. Sorry.

Why are we using `startOnLoad: false` and a custom call to  `mermaid.init`? Does it have to do with live preview mode?

Running `mermaid.init(undefined,document.querySelectorAll(".mermaid"));` (at https://emanote.srid.ca/tips/js/mermaid) manually from the browser console after the page has loaded displays the diagrams.

**Comment by srid** [comment]
> Why are we using `startOnLoad: false` and a custom call to `mermaid.init`?

No idea, TBH (I should have added a comment!). It was added in https://github.com/EmaApps/emanote/commit/75eab9ca10120e9c59d1ffbac7aa72268579cd9c

Let's change it to something that works.

**Comment by srid** [comment]
https://ema.srid.ca/guide/site is also broken, as a result.

**Comment by srid** [comment]
Maybe we should stop relying on CDN, and include the mermaid JS assets locally under https://github.com/EmaApps/emanote/tree/master/default/_emanote-static

**Comment by srid** [comment]
Fixed: https://emanote.srid.ca/tips/js/mermaid

by #371
