### ISSUE TITLE
When using live server, ctrl + click on any internal link does not open in new tab

### ISSUE THREAD

**Issue by tars0x9752** [srid/emanote#382]
**Describe the bug**

When using live server, `ctrl + click` on any internal link does not open in new tab. I think this is caused by ema instead of emanote, but I'm posting this here because I've faced this problem while using emanote.

I guess the click event is intercepted by the embedded JS code, which is probably where "`ctrl + click` to open in new tab" is disabled.

BTW I'm not having that much trouble, since it's only when using live server and I'm just reporting this in case it was a bug. Sorry if it's intended and not a bug.

**To Reproduce**
1. Launch the live server.
2. Open any page that has an internal link.
3. `ctrl + click` on an internal link.
4. New tab won't open. The link opens in the same tab instead.

**Expected behavior**

`ctrl + click` on a link will automatically open it in a new tab.

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: 107.0 (64-bit)

**Comment by srid** [comment]
I cannot reproduce this on macOS (where it is <kbd>Cmd+Click</kbd>), both on Brave and Firefox.

Either your issue is Linux or Windows only (can somebody else confirm?), or something unique to your environment (browser extensions getting in the way?).
