### ISSUE TITLE
Broken link in yaml docs

### ISSUE THREAD

**Issue by IllustratedMan-code** [srid/emanote#405]
**Describe the bug**
The link under "examples" in the [Yaml Configuration](https://emanote.srid.ca/guide/yaml-config) page is broken. It points to an `index.yaml` file that no longer exists.

**Comment by IllustratedMan-code** [comment]
This could probably go into a discussion, but I think that the yaml documentation in particular is very lacking. I think some kind of api style docs would be great, description of all options, available customizations, etc. I'm happy to help!

**Comment by srid** [comment]
> I think that the yaml documentation in particular is very lacking. I think some kind of api style docs would be great, description of all options, available customizations, etc. I'm happy to help!

Sure, open a new discussion in Discussions tab?

**Comment by srid** [comment]
I use this https://github.com/srid/emanote/blob/master/default/index.yaml as reference, but we could maybe generate a nice HTML docs from it. I don't know much about YAML toolset.
