### ISSUE TITLE
Stork search doesn't work with org files

### ISSUE THREAD

**Issue by IllustratedMan-code** [srid/emanote#413]
**Describe the bug**
org files do not appear to be indexed by stork. You can see this with my site: https://illustratedman-code.github.io/Planner/

Only the first page is markdown, the rest are org. I can only search the main index.md page.

**To Reproduce**
1. create emanote site with org-mode files
2. search something in the org-mode file

**Comment by srid** [comment]
@IllustratedMan-code Try #414 (`nix run github:srid/emanote/stork-org`).

**Comment by IllustratedMan-code** [comment]
That worked!
