### ISSUE TITLE
Add a flake template for Markdown notes

### ISSUE THREAD

**Issue by srid** [srid/emanote#421]
Should initialize the current folder of `.md` files with flake.nix of https://github.com/srid/emanote-template - and possibly another template that includes the whole jazz (.vscode, .github, index.yaml, index.md)

For use with https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake-init.html

**Comment by srid** [comment]
Use this opportunity to move https://github.com/srid/emanote/blob/master/nix/emanote.nix to its own repo, as flake-parts module cum template.

**Comment by shivaraj-bh** [comment]
@srid If it is still a consideration to move the `flakeModule` and `templates` to a repo of their own, I can close the PR above and raise it in the right one.

**Comment by srid** [comment]
Nah, it is fine. Let's keep it all in this repo.
