### ISSUE TITLE
Note not found page has status code 200

### ISSUE THREAD

**Issue by MaienM** [srid/emanote#430]
**Describe the bug**
Note not found page has status code `200`.

**To Reproduce**
1. Start live server.
2. Go to the url of a note that does not exist.
3. Get an error page.
4. Notice that the status code is `200`.

**Expected behavior**
The error pages should have appropriate status codes. For the node not found page this should probably be `404`, for the ambiguous note probably something in the 500 range.

**Screenshots**
![2023-04-03T10:53:52+0200-654x289](https://user-images.githubusercontent.com/583129/229472806-67f21800-61a7-48ca-b613-60614e7b5b1b.png)
![2023-04-03T11:03:31+0200-247x61](https://user-images.githubusercontent.com/583129/229472801-e60f53f6-38cf-4900-88f4-29f12ad98beb.png)

**Desktop (please complete the following information):**
 - Firefox 111.0.1
 - Emanote 1.0.2.0

**Additional context**
N/A

**Comment by srid** [comment]
Are you using the live server for serving production site (which it is not meant for)? What should happen during [hot reload](https://ema.srid.ca/topics/hot-reload) -- as opposed to manual page load? Anyway, this is all more a discussion for https://github.com/srid/ema
