### ISSUE TITLE
Nix closure size regression

### ISSUE THREAD

**Issue by edrex** [srid/emanote#462]
`nix run github:srid/emanote` => starts to download 5300MB of devdeps.

Meta: emanote nix builds have been perpetually broken as long as I've been paying attention, which has entirely prevented me from using it outside of occasional experiments. I'd like to fix it rather than writing it off, but I have limited resources and am losing faith.

**Comment by srid** [comment]
I don't know what's wrong the cachix cache; is #392 reoccurring?

[I cannot help with nixpkgs upstreaming](https://srid.ca/nixos-mod), but perhaps you can comment on https://github.com/NixOS/nixpkgs/issues/254999

**Comment by srid** [comment]
It is indeed cached, https://github.com/srid/srid/actions/runs/7024359318/job/19112915626

```
copying path '/nix/store/34qc8lllnb3712djk6p6kx4mrp0wvi7z-emanote-1.2.0.0' from 'https://srid.cachix.org/'...
```

So we just need to fix the regression in closure size.

**Comment by srid** [comment]
Closure size is back to normal: https://github.com/srid/emanote/pull/475
