### ISSUE TITLE
Show anchor links to each headings on hover

### ISSUE THREAD

**Issue by srid** [srid/emanote#480]
Note that this anchor can be overriden:

<img width="297" alt="image" src="https://github.com/srid/emanote/assets/3998/d2bd8422-a4ef-450e-8298-d0f117660913">

When rendered in HTML, it'd be good to have a `#` link as docusaurus shows on hover: 
<img width="305" alt="image" src="https://github.com/srid/emanote/assets/3998/7814f152-9344-467d-bd1e-d3e53a422f62">

Past discussion:

- https://github.com/srid/emanote/discussions/137
- https://github.com/srid/emanote/discussions/478

**Comment by TristanCacqueray** [comment]
Hello @srid , I'd like to work on this. Not sure what you had in mind, but do you think we could modify the noteDoc in `renderLmlHtml` using such a transformation?:

```haskell
addSectionLinks :: Pandoc -> Pandoc
addSectionLinks = walk f
  where
    f (Header n attr@(idAttr, _, _) inlines) =
        let link = Link ("", ["anchor"], []) [Str "§"] ("#" <> idAttr, "")
         in Header (n + 1) attr ([link, Space] <> inlines)
    f x = x
```

**Comment by srid** [comment]
@TristanCacqueray 

Sure, you can work on this. I was thinking more like doing that HTML layout in `pandoc.tpl` here:

https://github.com/srid/emanote/blob/bf573e7653d183baa0fa68e2e172333f585b7a25/emanote/default/templates/components/pandoc.tpl#L99-L106

Possibly similar to how we do for footnotes:

https://github.com/srid/emanote/blob/bf573e7653d183baa0fa68e2e172333f585b7a25/emanote/default/templates/components/pandoc.tpl#L47-L53

This would allow the user to customize their apperance in `.tpl` without needing to fork emanote.

Doing this however might require some Haskell changes; I haven't taken a good look at that code yet.

**Comment by TristanCacqueray** [comment]
Great, thanks for the footnote example. I guess we need a change in `Heist.Extra.Splices.Pandoc` to pass the heading id and content?

**Comment by srid** [comment]
I think you need to edit https://github.com/srid/heist-extra/blob/master/src/Heist/Extra/Splices/Pandoc/Render.hs

Checkout how other non-trivial nodes are rendered, like `DefinitionList`.

One possible shape:

```html
<Header>
  <Header:Main>
     <h1 class="pb-2 mb-2 text-5xl font-bold text-center"> <inlines /> </h1>
     ...
  </Header:Main>
  <!-- custom HTML goes here, or above -->
  <a href="...">#${header:anchor}</a>
</Header>
```

Or something like that.

**Comment by TristanCacqueray** [comment]
Ok, so I managed to get something working with:

```
  <Header>
    <Header:Main>
      <h2 id="${header:id}" class="mt-6 mb-4 text-4xl font-bold text-gray-700 border-b-2"> <inlines /> </h2>
    </Header:Main>
    <a href="#${header:id}">⛓</a>
  </Header>
```

Though I'm not familiar with heist. Should we make one splice (e.g. Header:Main1, Header:Main2, ...) per levels?
I don't understand how the default template renders one of the `hN` element correctly with:

```
  <Header>
    <h1 class="pb-2 mb-2 text-5xl font-bold text-center" />
    <h2 class="mt-6 mb-4 text-4xl font-bold text-gray-700 border-b-2" />
  </Header>
```

… but once I add the `<inlines />` then it works differently, e.g. this render both h1 and h2:

```
  <Header>
    <Header:Main>
      <h1 class="pb-2 mb-2 text-5xl font-bold text-center"> <inlines /> </h1>
      <h2 id="${header:id}" class="mt-6 mb-4 text-4xl font-bold text-gray-700 border-b-2"> <inlines /> </h2>
    </Header:Main>
  </Header>
```

I must be doing something wrong in https://github.com/srid/heist-extra/pull/6 , could you please have a look when you have a moment? Thanks in advance!

**Comment by srid** [comment]
Hey @TristanCacqueray - could you open a draft PR in emanote with what you have? I'll play with it.

(I might be late to respond due to https://nixos.asia/en/event/srid-nix-dev and other things)

**Comment by TristanCacqueray** [comment]
Sure, good luck with your demo!

**Comment by srid** [comment]
Just took a brief look:

> I don't understand how the default template renders one of the hN element correctly with:

Because of https://github.com/srid/heist-extra/blob/54ff970f733dd45b5509d1c4c298927b6241041b/src/Heist/Extra/Splices/Pandoc/Ctx.hs#L106-L110

---

I think perhaps this would be simpler and clear?

```html
<Header>
  <Header:2>
    <h2 id="${header:id}" class="mt-6 mb-4 text-4xl font-bold text-gray-700 border-b-2">
      <inlines />
      <a href="#${header:id}">⛓</a>
    </h2>
  </Header:2>
  <!-- ... Likewise, for 1, 3-7 -->
</Header>
```

We may be able to DRY-refactor the anchor HTML using `<bind tag="..">`, cf. https://github.com/srid/emanote/blob/b38035c258d1a44d882a768b2747e6b88e507709/emanote/default/templates/layouts/default.tpl#L5-L11 (not sure if it can take 'arguments').
