### ISSUE TITLE
Latest Docker image (March 2024) not starting

### ISSUE THREAD

**Issue by allofmex** [srid/emanote#534]
**Describe the bug**
The latest docker image does not start up. 

**To Reproduce**
`docker run sridca/emanote`

Results in error
`unable to start container process: exec: "/nix/store/vms882x77jvwg630sdv81vdd5k0jklwn-emanote-1.3.14.3/bin/emanote": stat /nix/store/vms882x77jvwg630sdv81vdd5k0jklwn-emanote-1.3.14.3/bin/emanote: no such file or directory: unknown.`

(Please also use version tags additional to `latest` for the docker image in the future. That way we will be able to fallback to a previous version in cases like this)

**Desktop:**
Docker version 25.0.2
Kernel 6.5.0-26-generic
Ubuntu 23.10

**Comment by srid** [comment]
I recently stopped supporting Docker. See https://github.com/srid/emanote/pull/524

**Comment by srid** [comment]
And it is back: https://emanote.srid.ca/container
