### ISSUE TITLE
Support Math in note link titles

### ISSUE THREAD

**Issue by srid** [srid/emanote#57]
Requested by @bradleyharden

Basically the following note Markdown,

```markdown
# $a+b^2$, a formula

Content...
```

Should render the Math formula wherever the note title is used (eg: in sidebar, or links).

To test this, you'll need to use either MathJax or Katex JS in here,

https://github.com/srid/emanote/blob/78c9a2cf39d20fd90015e810b6d244cc270df49e/default/index.yaml#L47-L50

To implement this, see #62

**Comment by srid** [comment]
@bradleyharden Can you try the latest `master` branch and let me know if this is working or not? It may be glitchy on live-server - but it should reliably work on the generated site.

**Comment by bradleyharden** [comment]
Yes, it works
