### ISSUE TITLE
mailto: links should not be handled like resource links

### ISSUE THREAD

**Issue by srid** [srid/emanote#69]
Use `foo@bar.com` in Markdown, and Emanote will render it as a broken link.

Fix: change emanote to be aware of `mailto:` protocol, and ignore handling it. 

Potential solution: add another `guard` in here: 

https://github.com/srid/emanote/blob/8fb4aa8cfaf097a61b474365a96b19b512a363c2/src/Emanote/Model/Link/Rel.hs#L80-L82

**Comment by carliros** [comment]
I see this
```
-- TODO: Handle mailto: etc.
```
in WikiLinks.hs, line 53. 
I think we need to remove that, correct? Because that is being addressed in Rel.hs

Same for line 54. This is repetitive, correct?

**Comment by srid** [comment]
Resolved by #72

> I think we need to remove that, correct? Because that is being addressed in Rel.hs

Ah, yes, you are right. Good catch.
