### ISSUE TITLE
Custom wiki-link text doesn't work if it is same as filename

### ISSUE THREAD

**Issue by srid** [srid/emanote#77]
1. Create foo.md and add `# Foo Title` to it.
2. In another note, link to it as `[[foo]]` and verify that it appears at "Foo Title".
3. Now use a custom text, as `[[foo|foo]]`, and notice the bug - of nothing changing.

Possible fix: compare with title instead of url in here: https://github.com/srid/emanote/blob/d4e973e8f821a2f921ad8497b425c03cf19dab94/src/Emanote/Pandoc/Filter/Url.hs#L79-L81

**Comment by carliros** [comment]
@srid,

is there a way to disambiguate `[[foo]]` and `[[foo|foo]]` ?

I see that Pandoc Link is defined as
```
Link Attr [Inline] Target  -- ^ Hyperlink: alt text (list of inlines), target
```
For example, if we define ex1 as `[[foo|Alternative]]` and ex2 as `[[foo|foo]]` and ex3 as `[[foo]]`,
we get the following instances
```
Link ("",[],[("data-wikilink-type","WikiLinkNormal")]) [Str "Alternative"] ("foo","")  --ex1
Link ("",[],[("data-wikilink-type","WikiLinkNormal")]) [Str "foo"] ("foo","") --ex2
Link ("",[],[("data-wikilink-type","WikiLinkNormal")]) [Str "foo"] ("foo","") --ex3
```

Considering `[Inline]` is the alternative text, example 1 and 2 are correct, but example 3 might be wrong, 
I guess that should be empty list ([]). I do not see a way to disabiguate example 2 and 3. Is there a way?
is it a bug on Pandoc?

On the other hand, you suggested to use the title instead of url. In the three examples, the title is not filled, 
it is always empty! 

Any suggestions?

**Comment by srid** [comment]
@carliros Hmm, I think your idea -- of making the inline an empty list in the 3rd case -- would be better.

Currently, plain wiki-links just automatically fill in the inline with the URL; it happens here (the `CM.str title`): 

https://github.com/srid/emanote/blob/4eaed83f7a8d8bcbf922abf56784740e9693b5e4/src/Emanote/Pandoc/Markdown/Syntax/WikiLink.hs#L153

The "fill in" itself happens here:

https://github.com/srid/emanote/blob/4eaed83f7a8d8bcbf922abf56784740e9693b5e4/src/Emanote/Pandoc/Markdown/Syntax/WikiLink.hs#L145-L146

So instead of `M.option url` we can propagate the optional type (Maybe) as-is to the [HasWikilink](https://github.com/srid/emanote/blob/4eaed83f7a8d8bcbf922abf56784740e9693b5e4/src/Emanote/Pandoc/Markdown/Syntax/WikiLink.hs#L104-L110) type class and have it fill in empty inlines on Nothing. 

(Note that here we are in the [commonmark](https://github.com/jgm/commonmark-hs) territory; it is a Markdown parser by the same author of Pandoc; and it gives us back a Pandoc AST -- and that's what the HasWikilink type class enabes, the construction of a specific AST node; IIRC, pandoc now uses this as its markdown parser).

That's something to explore ... and we should make sure that this change doesn't introduce any regressions (links should continue to render as before, including broken wiki-links - which are rendered normally except for a strikethrough).

**Comment by carliros** [comment]
Got it. So, it is a custom syntax for Pandoc! That is cool. 
Working on the 3rd approach.

**Comment by srid** [comment]
Yes, wiki-link is our custom extension on top of Pandoc (implemented as commonmark-hs extension). 

We also have one for Twitter-like hashtags: https://github.com/srid/emanote/blob/4eaed83f7a8d8bcbf922abf56784740e9693b5e4/src/Emanote/Pandoc/Markdown/Syntax/HashTag.hs
