### ISSUE TITLE
Render Tasks lists

### ISSUE THREAD

**Issue by srid** [srid/emanote#78]
The following Markdown,

```markdown
- [ ] Foo
- [ ] Bar
```

currently renders as,

![image](https://user-images.githubusercontent.com/3998/122847635-16115100-d2d6-11eb-9826-e955d327e85e.png)

The checkboxes should be styled like task lists. See https://tailwindcss.com/docs/hover-focus-and-other-states#checked

**Comment by Beatrix-droid** [comment]
May I work on this issue please?

(EDIT: [user opened spam PR](https://github.com/srid/emanote/pull/80))
