### ISSUE TITLE
Allow inline embedding images

### ISSUE THREAD

**Issue by srid** [srid/emanote#98]
The following works,

```markdown
Para 1

![[Foo.jpeg]]

Para 2
```

But the following does not,

```markdown
A paragraph that contains an image: ![[Foo.jpeg]]
```

See https://github.com/srid/emanote/discussions/97 for background

**Comment by carliros** [comment]
@srid
I've been reviewing it, do you think it is a good idea to add the change on Embed.embedWikiLinkResolvingSplice ?
I saw that it recognize a `Para[Link {..}]` only, I think we can change that to verify if there is some Link in the Blocks of Para, and then create the slices for each Link... do you think it is a good idea?

**Comment by srid** [comment]
> I saw that it recognize a Para[Link {..}] only, I think we can change that to verify if there is some Link in the Blocks of Para, and then create the slices for each Link... do you think it is a good idea?

No, but consider that there are two renderers:

- `PandocBlockRenderer` (Renderer/Embed.hs uses this)
- `PandocInlineRenderer` (Renderer/Url.hs uses this)

The solution here is to make the image embed renderer use `PandocInlineRenderer`, but leave the note embedding to use `PandocBlockRenderer`. So Embed.hs can just expose two functions:

- `embedInlineWikiLinkResolvingSplice` (deals with images, audio, etc..)
- `embedBlockWikiLinkResolvingSplice` (deals with notes, PDFs, videos, etc..)
 
This approach makes it simpler to implement, since you don't have to traverse the Para for links (it won't capture all edge cases anyway). That's what an "inline renderer" gives you; ability to override rendering of specific inlines (without regards to their block context).

**Comment by srid** [comment]
By the way, feel free to take a stab it. It is a good feature task to take your Emanote contribution to 'next level'. :-)
