### ISSUE TITLE
List bullets are out of alignment in complex items

### ISSUE THREAD

**Issue by srid** [srid/emanote#99]
> I also wanted to point out that the bullet styling is a bit off sometimes. The text shows below the bullet point instead of beside it. 
> 
> ![image](https://user-images.githubusercontent.com/63365609/124153824-7a8c9700-dab2-11eb-9aee-e12d764bce82.png)
> 
> Here is an [example note:](https://n.xygn.us/C-Notes/Core/Pathology/Systemic/2.%20Inflammation)  
> [Source](https://gist.githubusercontent.com/xygn/10b6e9d75ef9368b40663d7b97bf03c9/raw/088195dc53c943070fb66c75b7d4302cebff31d9/Inflammation.md)

_Originally posted by @xygn in https://github.com/srid/emanote/discussions/97#discussioncomment-950194_

**Comment by xygn** [comment]
[Generated HTML file](https://github.com/xygn/Notes/blob/gh-pages/C-Notes/Core/Pathology/Systemic/2.%20Inflammation.html)

[Source files](https://github.com/xygn/Notes)

**Comment by srid** [comment]
Also happens when using tasklists and the list item overflows to next line,

![image](https://user-images.githubusercontent.com/3998/124207713-1cf94a00-dab4-11eb-889c-f29029c2fd84.png)

**Comment by carliros** [comment]
Digging into this issue, looks like this is a pandoc formatting issue. I notice the issue is happening when there are two bullet lists separated by an empty line. When that happens, it is adding some paragraphs on list items.

For example:
```
Rendering lists

- item_1 list_1
- item_2 list_1

- item_1 list_2
```

The generated code is this
```
Para [Str "Rendering",Space,Str "lists"]
BulletList 
  [ [Para [Str "item_1",Space,Str "list_1"]]
  , [Para [Str "item_2",Space,Str "list_1"]]
  , [Para [Str "item_1",Space,Str "list_2"]]]
```

Those paragraphs are causing the alignment issue.

But, if we add some text to make sure that second list is a diffirent block, then it just works fine. Like this:
```
Rendering lists

- item_1 list_1
- item_2 list_1

Para
- item_1 list_2
```

This would end up as
```
Para [Str "Rendering",Space,Str "lists"]
BulletList 
  [ [Plain [Str "item_1",Space,Str "list_1"]]
  , [Plain [Str "item_2",Space,Str "list_1"]]]
Para [Str "Para"]
BulletList 
  [[Plain [Str "item_1",Space,Str "list_2"]]]
```

Notice that instead of `Para` it used `Plain`.

Adding some text to make sure we have two lists could be workaround. Any ideas on what to do?

**Comment by carliros** [comment]
Another workaround to have two continuous list would be to use a different bullet symbol, like this:

```
Rendering lists

- item_1 list_1
- item_2 list_1

* item_1 list_2
```

That will work just fine as well.

**Comment by srid** [comment]
That's one trigger for this bug, yes. To address that, perhaps we can do a special case check for bulletlist item with exactly one `Para` and convert that to `Plain` before rendering. Out of curiosity, I wonder how pandoc's (or commonmark's) own HTML writer deals with it.

The other trigger is the HTML generated by task lists: https://github.com/srid/emanote/issues/99#issuecomment-872650108 ... one solution here is to stop using *native* list bullets (ie, the `list-disc` class) entirely, and do our own bullets in CSS using flexbox (we already do this for definition lists).

**Comment by carliros** [comment]
I just see commonmark-pandoc does the same as your suggestion!

https://github.com/jgm/commonmark-hs/blob/344d380edc1f44ab476d176050263b92d9bfd411/commonmark-pandoc/src/Commonmark/Pandoc.hs#L160

**Comment by carliros** [comment]
I added the PR for converting Para into Plain.

I am not sure how to do the other part for list styles using flexbox.
